### ISSUE TITLE
Repodata is not regenerated after package is removed

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/subatomic#22]
## How to reproduce

1. `sha256sum <REPO/repodata.xml>`
2. `subatomic-cli repo d <REPO> <PACKAGE>` or relevant REST API call
3. `sha256sum <REPO/repodata.xml>` again

## Expected result

SHA256 checksum changes, indicating that repodata has been regenerated

**Comment by lleyton** [comment]
see latest release
